# Generated by Django 3.1.1 on 2021-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Deliver_anywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='Local_Delivery_Distance',
            field=models.IntegerField(default=0),
        ),
    ]
