# Generated by Django 3.1.1 on 2021-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20210807_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Premium_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Premium_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
