# Generated by Django 3.1.1 on 2021-08-07 13:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0007_auto_20210807_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Unique_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Buyer_Name', models.CharField(max_length=20)),
                ('Buyer_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Buyer_Email', models.EmailField(max_length=254)),
                ('Buyer_pincode', models.IntegerField(max_length=6)),
                ('Order_Personalisation_Description', models.CharField(max_length=254)),
                ('Message', models.CharField(max_length=50)),
                ('Communication', models.BooleanField(default=True)),
                ('Order_Confirmation', models.BooleanField(default=False)),
                ('Order_fulfilled', models.BooleanField(default=False)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Review_Description', models.CharField(max_length=254)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Description', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
        ),
    ]
