# Generated by Django 3.1.1 on 2021-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Buyer_pincode',
            field=models.CharField(max_length=6),
        ),
    ]
