# Generated by Django 3.1.1 on 2021-08-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210807_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Starting_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
