# Generated by Django 3.1.1 on 2021-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_product_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Image_1',
            field=models.ImageField(default='product_image1.jpg', upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image_2',
            field=models.ImageField(default='product_image2.jpg', upload_to='product_image'),
        ),
    ]
